---
title: "506 Group Project Suggestion" 
author: "Thomas Fiore"
date: "`r format.Date(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE)
```

The following three topics together might make a nice self-contained project, that could be done in 3 languages. 

## Representing Time Series Data   
## Plotting Time Series Data
## Computing a Moving Average

These three topics are covered using the \texttt{zoo} package in R in Sections 14.1, 14.2, and 14.10 of the R Cookbook by Paul Teetor. The \texttt{zoo} package creates \texttt{zoo} objects with nice functionality, better than \texttt{ts} classes in base R. 

Presumably the three topics could also be done in base R using \texttt{ts} objects. I think that is what they do here: 
https://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/

Here are many data sets on time series. 

https://datamarket.com/data/list/?q=provider:tsdl

These three topics could be done in Python and Stata. Or, perhaps in \texttt{zoo}, base R, and Python. The R cookbook is straightforward, so the \texttt{zoo} package would be easiest. The other link may be useful for base R. 


